trigger:
  branches:
    include:
      - local
      - dev
pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: 'dev-variable-group'

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: BuildJob
        displayName: 'Build Job'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '14.x'
            displayName: 'Install Node.js'

          - script: |
              npm install
            displayName: 'Install dependencies and build'

  - stage: Deploy
    displayName: 'Deploy Stage'
    jobs:
      - job: DeployJob
        displayName: 'Deployment Job'
        steps:
          - script: |
              aws configure set aws_access_key_id $(AWS_ACCESS_KEY_ID)
              aws configure set aws_secret_access_key $(AWS_SECRET_ACCESS_KEY)
              aws configure set default.region $(AWS_DEFAULT_REGION)
            displayName: 'AWS CLI Configuration'

          - script: |
              cd fortress-store-portal-ui/
              aws cloudformation validate-template --template-body file://portal.yml
              aws cloudformation deploy --stack-name fortress-stack-ui-dev --template-file portal.yml --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM --parameter-overrides Env=$(Env)
            displayName: 'Deploying distribution'

          - script: |
              cd fortress-store-portal-ui/
              export CI=false
              npm install 
              npm run build
              aws s3 rm s3://fortress-stack-ui-$(Env)/ --recursive
              aws s3 sync ./dist s3://fortress-stack-ui-$(Env)/
              aws cloudfront create-invalidation --distribution-id $(cfd_id) --paths "/*"
            displayName: 'Deploying to S3 bucket'
