name: Build and Deploy

on:
  push:
    # types: [opened, synchronize, reopened, closed]
    branches:
      - gh-pages  

jobs:
  unit_tests:
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.action == 'reopened')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Unit-tests
        run: |
          npm i
          npm run test 

  code-deploy:
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' && (github.ref == 'refs/heads/poc') || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop')
    environment:
      name: poc
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-duration-seconds: 1200
          audience: sts.amazonaws.com

      - name: Set up .env file
        env:
          VITE_APP_SESSION: ${{ secrets.VITE_APP_SESSION }}
          VITE_APP_BASE_URL: ${{ secrets.VITE_APP_BASE_URL }}
        run: |
          echo "VITE_APP_SESSION=${{ secrets.VITE_APP_SESSION }}" >> .env.${{ secrets.ENV }} 
          echo "VITE_APP_BASE_URL=${{ secrets.VITE_APP_BASE_URL }}" >> .env.${{ secrets.ENV }} 

      - name: Deploying distribution
        env:
          ENV: ${{ secrets.ENV }}
          VITE_APP_SESSION: ${{ secrets.VITE_APP_SESSION }}
          VITE_APP_BASE_URL: ${{ secrets.VITE_APP_BASE_URL }}
        run: |
          aws cloudformation validate-template --template-body file://portal.yml
          aws cloudformation deploy --stack-name test-stack-ui-${{ secrets.ENV }} --template-file portal.yml --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM --parameter-overrides Env=${{ secrets.ENV }}      

      - name: Build and Deploying FE Code
        env:
          CFD_ID: ${{ secrets.CFD_ID }}
        run: |
          # printenv >  .env.${{ secrets.ENV }}
          npm install
          export CI=false
          npm run build:${{ secrets.ENV }}
          cat .env.${{ secrets.ENV }}
          aws s3 rm s3://test-stack-ui-${{ secrets.ENV }}/ --recursive
          aws s3 sync ./dist s3://test-stack-ui-${{ secrets.ENV}}/
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CFD_ID }} --paths "/*"

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Update apt-get
        run: sudo apt-get update

      - name: Fix broken dependencies
        run: sudo apt --fix-broken install -y

      - name: Set up Maven and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y maven libasound2 libasound2-data libnspr4 libnss3 default-jre-headless libjansi-java libmaven3-core-java libwagon-file-java libwagon-http-shaded-java jq

      - name: Googledriver setup
        run: |
          sudo apt install wget -y
          sudo apt install unzip -y
          wget https://dl.google.com/linux/deb/pool/main/g/google-chrome-stable/google-chrome-stable_126.0.6478.126-1_amd64.deb
          sudo dpkg -i google-chrome-stable_126.0.6478.126-1_amd64.deb
          wget https://storage.googleapis.com/chrome-for-testing-public/126.0.6478.126/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip  
          sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chown runner:runner /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Install xvfb
        run: sudo apt-get install -y xvfb

      - name: Set up .env file
        env:
          CFD_URL: ${{ secrets.CFD_URL }}
        run: |
          echo "url=${{ secrets.CFD_URL }}" > automation-testing/src/main/java/zapcg/Capillary/Base/config.properties

      - name: Start xvfb and run tests
        run: |
          export DISPLAY=:99
          cd automation-testing/
          xvfb-run -a mvn clean install

      - name: Upload test report artifact
        uses: actions/upload-artifact@v4
        with:
          name: TestReport
          path: automation-testing/reports/index.html
          if-no-files-found: warn

      - name: Set RUN_ID output
        id: set-outputs
        run: echo "run_id=${{ github.run_id }}" >> $GITHUB_ENV

      - name: Configure AWS CLI
        run: |
          sudo apt-get install -y awscli
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1

      - name: Upload Report to S3
        run: |
          aws s3 cp automation-testing/reports/index.html s3://test-stack-ui-poc-poc/${{ github.run_id }}/index.html

      - name: Set REPORT_URL output
        env:
          REPORT_CFD_URL: ${{ secrets.REPORT_CFD_URL }}
          REPORT_CFD_ID: ${{ secrets.REPORT_CFD_ID }}
        run: |
          echo "report_url=${{ secrets.REPORT_CFD_URL }}/${{ github.run_id }}/index.html" >> $GITHUB_ENV
          aws cloudfront create-invalidation --distribution-id ${{ secrets.REPORT_CFD_ID }} --paths "/*"

      - name: Sending Reporting to Slack
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          RUN_ID: ${{ env.run_id }}
          REPORT_URL: ${{ env.report_url }}
        run: |
          cd automation-testing/
          bash git.sh        

  # notify_on_success:
  #   runs-on: ubuntu-latest
  #   needs: deploy
  #   environment:
  #     name: poc
  #   if: success()
  #   steps:
  #     - name: Notify Slack for pipeline success
  #       env:
  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  #         REPO_NAME: ${{ secrets.REPO_NAME }}
  #         ENVIRONMENT: ${{ secrets.ENV }}  
  #         REPO_SLUG: ${{ secrets.REPO_SLUG }}
  #       run: |
  #         curl -X POST -H 'Content-type: application/json' --data '{
  #           "text": "GitHub Pipeline Status Notification",
  #           "attachments": [
  #             {
  #               "fields": [
  #                 {
  #                   "title": "Repository",
  #                   "value": "'${REPO_NAME}'"
  #                 },
  #                 {
  #                   "title": "Environment",
  #                   "value": "'${ENVIRONMENT}'"
  #                 },
  #                 {
  #                   "title": "Status",
  #                   "value": "SUCCESS",
  #                   "color": "00FF00"
  #                 },
  #                 {
  #                   "title": "Pipeline URL",
  #                   "value": "https://github.com/${{ secrets.REPO_SLUG }}/${{ secrets.REPO_NAME }}/actions/runs/${{ github.run_id }}"
  #                 },
  #                 {
  #                   "title": "Branch",
  #                   "value": "${{ github.ref }}"
  #                 }
  #               ]
  #             }
  #           ]
  #         }' $SLACK_WEBHOOK_URL

  # notify_on_failure:
  #   runs-on: ubuntu-latest
  #   needs: deploy
  #   environment:
  #     name: poc
  #   if: failure()
  #   steps:
  #     - name: Notify Slack for pipeline failure
  #       env:
  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  #         REPO_NAME: ${{ secrets.REPO_NAME }}
  #         ENVIRONMENT: ${{ secrets.ENV }} 
  #         REPO_SLUG: ${{ secrets.REPO_SLUG }}
  #       run: |
  #         curl -X POST -H 'Content-type: application/json' --data '{
  #           "text": "GitHub Pipeline Status Notification",
  #           "attachments": [
  #             {
  #               "fields": [
  #                 {
  #                   "title": "Repository",
  #                   "value": "'${REPO_NAME}'"
  #                 },
  #                 {
  #                   "title": "Environment",
  #                   "value": "'${ENVIRONMENT}'"
  #                 },
  #                 {
  #                   "title": "Status",
  #                   "value": "FAILED",
  #                   "color": "#FF0000"
  #                 },
  #                 {
  #                   "title": "Pipeline URL",
  #                   "value": "https://github.com/${{ secrets.REPO_SLUG }}/${{ secrets.REPO_NAME }}/actions/runs/${{ github.run_id }}"
  #                 },
  #                 {
  #                   "title": "Branch",
  #                   "value": "${{ github.ref }}"
  #                 }
  #               ]
  #             }
  #           ]
  #         }' $SLACK_WEBHOOK_URL

  # delete-branch:
  #   runs-on: ubuntu-latest
  #   needs: deploy
  #   if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop'
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     - name: Delete branch
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  #       run: |
  #         branch=${{ github.event.pull_request.head.ref }}
  #         if [[ "$branch" != feature/* ]] && [[ "$branch" != feat/* ]]; then
  #           git remote set-url origin https://x-access-token:${ACCESS_TOKEN}@github.com/${{ github.repository }}
  #           git push origin --delete $branch
  #         fi
