name: Build and Deploy

on:
  push:
    branches:
      - feature/test-purpose
jobs:

  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: |
          env

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-duration-seconds: 1200
          audience: sts.amazonaws.com  

      - name: Deploying distribution
        run: |
          aws s3 ls