on:
  push:
    branches:
      - schedule-job-check

permissions:
  contents: write

jobs:
  pull-request:
    runs-on: ubuntu-latest
    environment:
      name: poc
    steps:
      - uses: actions/checkout@v3

      # Create a pull request with reviewers
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          commit-message: Automated PR creation
          branch: automated-pr
          base: develop
          title: Automated Pull Request
          body: This is an automated pull request.
          reviewers: |
            bablubharath
