on:
  push:
    branches:
      - "schedule-job-check"

jobs:
  pull-request:
    runs-on: ubuntu-latest
    environment:
      name: poc
    steps:
      # - uses: actions/checkout@v3
      # - name: pull-request
      #   uses: diillson/auto-pull-request@v1.0.1
      #   with:
      #     source_branch: "schedule-job-check"
      #     destination_branch: "develop"
      #     pr_title: "Pulling ${{ github.ref }} into develop"
      #     pr_body: |
      #       :crown: *An automated PR*
      #     pr_reviewer: "bablubharath"
      #     pr_label: "auto-pr"
      #     pr_allow_empty: true
      #     github_token: ${{ secrets.ACCESS_TOKEN }}
      - name: Unit-tests
        run: |
          echo "Printing Env Variables"
          env
          echo "Printing Env Variables To A File"
          printenv > .env.${{ secrets.ENV }}
          echo "Reading The File"
          cat .env.${{ secrets.ENV }}
          echo "============================"