on:
  push:
    branches:
      - schedule-job-check

permissions:
  contents: write

jobs:
  pull-request:
    runs-on: ubuntu-latest
    environment:
      name: poc
    steps:
      - uses: actions/checkout@v3
      - name: pull-request
        uses: diillson/auto-pull-request@v1.0.1
        with:
          destination_branch: "develop"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
