name: Build and Deploy

on:
  push:
    branches:
      - latest-code
  workflow_dispatch:
  pull_request:
    branches:
      - latest-code

jobs:
  automation_testings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 🔎 Check IP
        run: curl https://api.ipify.org  

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Update apt-get
        run: sudo apt-get update

      - name: Fix broken dependencies
        run: sudo apt --fix-broken install -y

      - name: Set up Maven and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y maven libasound2 libasound2-data libnspr4 libnss3 default-jre-headless libjansi-java libmaven3-core-java libwagon-file-java libwagon-http-shaded-java

      - name: Googledriver setup
        run: |
          sudo apt install wget -y
          sudo apt install unzip -y
          wget https://dl.google.com/linux/deb/pool/main/g/google-chrome-stable/google-chrome-stable_126.0.6478.126-1_amd64.deb
          sudo dpkg -i google-chrome-stable_126.0.6478.126-1_amd64.deb
          wget https://storage.googleapis.com/chrome-for-testing-public/126.0.6478.126/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip  
          sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chown runner:runner /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Install xvfb
        run: sudo apt-get install -y xvfb

      - name: Start xvfb
        run: |
          export DISPLAY=:99
          cd automation-testing/
          xvfb-run -a mvn clean install 

      - name: artifact
        uses: actions/upload-artifact@v3
        with:       
            name: Report
            path: ("user.dir")+"\\reports\\index.html    

