name: DevSecOps check

on:
  push:
    branches:
      - "devsecops-check"

jobs:
  deploys:
    runs-on: ubuntu-latest
    environment:
      name: poc

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Report check
        run: |
          npm install  

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run OWASP Dependency-Check
        uses: docker://owasp/dependency-check:latest
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        with:
          args: --project "github-actions" --out /results --scan /github/workspace --nvdApiKey=${{ secrets.NVD_API_KEY }} --verbose


      - name: Upload Dependency-Check report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: /results/dependency-check-report.html