name: Build and Deploy

on:
  push:
    branches:
      - latest-code
  workflow_dispatch:
  pull_request:
    branches:
      - latest-code

jobs:
  automation_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Install Chrome browser
        uses: browser-actions/setup-chrome@latest

      - name: Verify Chrome installation
        run: google-chrome --version

      - name: Build with Maven
        working-directory: automation-testing
        run: mvn test 