name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 'latest'

    - name: Set up ChromeDriver
      uses: actions/checkout@v2
      uses: nanasess/setup-chromedriver@v1
      with:
        chrome-version: 'latest'

    - name: Verify Chrome and ChromeDriver versions
      run: |
        google-chrome --version
        chromedriver --version

    - name: Run tests with Maven
      run: |
        export DISPLAY=:99
        xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' mvn clean install
