name: Java CI with Maven

on:

  push:

    branches: [ latest-code ]


jobs:
  automation_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11.0.22'
          distribution: 'adopt'
          cache: maven
      - name: Print Java version
        run: java -version
      - name: Print Maven version
        run: mvn -version
      
      - name: Set up Chrome
        run: |
          - uses: actions/checkout@v2
          - uses: nanasess/setup-chromedriver@v2
          - run: |
              export DISPLAY=:99
              chromedriver --url-base=/wd/hub &
              sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1
              cd automation-testing/
              mvn clean
              mvn compile
              mvn install