name: Java CI with Maven

on:

  push:

    branches: [ latest-code ]


jobs:
  automation_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11.0.22'
          distribution: 'adopt'
          cache: maven
      - name: Print Java version
        run: java -version
      - name: Print Maven version
        run: mvn -version
      # - name: Set up Chrome
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y google-chrome-stable
      #     sudo apt-get install -y xvfb

      # - name: Set up ChromeDriver
      #   run: |
      #     CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
      #     wget -N https://chromedriver.storage.googleapis.com/${CHROME_VERSION}/chromedriver_linux64.zip
      #     unzip chromedriver_linux64.zip -d /usr/local/bin

      # - name: Verify Chrome and ChromeDriver versions
      #   run: |
      #     google-chrome --version
      #     chromedriver --version

      - name: Build with Maven
        run: |
          cd automation-testing/
          mvn clean
          mvn compile
          mvn install