name: Java CI with Maven

on:
  push:
    branches: [ latest-code ]

jobs:
  automation_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11.0.22'
          distribution: 'adopt'
          cache: maven
    
      - name: Install Chrome browser
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y xvfb
          sudo apt-get install -y libxi6 libgconf-2-4
  
      - name: Download Chrome Driver
        run: |
          sudo apt-get install -y unzip
          curl -sS -o chromedriver.zip https://chromedriver.storage.googleapis.com/$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          unzip chromedriver.zip -d /usr/local/bin/
          rm chromedriver.zip
  
      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1280x1024x24 &
          export DISPLAY=:99
          sleep 3 # Give Xvfb some time to start
  
      - name: Print Xvfb Display Status
        run: |
          ps -ef | grep Xvfb
  
      - name: Run Selenium tests
        run: |
          export DISPLAY=:99
          cd automation-testing/
          mvn clean install
          # Print the test results
          cat target/surefire-reports/*.txt
