name: DevSecOps check

on:
  push:
    branches:
      - "devsecops-check"

jobs:
  deploys:
    runs-on: ubuntu-latest
    environment:
      name: poc

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Report check
        run: |
          npm install  

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run OWASP Dependency-Check
        uses: docker://owasp/dependency-check
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }} 
        with:
          args: --project "github-actions" --out /results --scan /github/workspace --nvdApiKey=${{ secrets.NVD_API_KEY }}

      - name: Upload Dependency-Check report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: /results/dependency-check-report.html

  # sonarqube-analysis:
  #   runs-on: ubuntu-latest
  #   needs: deploys
  #   services:
  #     sonarqube:
  #       image: sonarqube:latest
  #       ports:
  #         - 9000:9000
  #       options: >-
  #         --health-cmd="curl -f http://localhost:9000/api/system/health || exit 1"
  #         --health-interval=30s
  #         --health-timeout=10s
  #         --health-retries=3