name: DevSecOps check

on:
  push:
    branches:
      - "devsecops-check"

jobs:
  deploys:
    runs-on: ubuntu-latest
    environment:
      name: poc

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npm install  

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run OWASP Dependency-Check
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/src \
            owasp/dependency-check:latest \
            dependency-check.sh --purge \
              --project "github-actions" \
              --scan /src \
              --nvdApiKey=${{ secrets.NVD_API_KEY }} \
              --format "HTML" \
              --out /src/dependency-check-report.html \
              --log /src/dependency-check.log

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: |
            ./dependency-check-report.html
            ./dependency-check.log
