name: DevSecOps check

on:
  push:
    branches:
      - "devsecops-check"

jobs:
  deploys:
    runs-on: ubuntu-latest
    environment:
      name: poc

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Report check
        run: npm install  

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run OWASP Dependency-Check
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/src \
            -v ${{ github.workspace }}/dependency-check-data:/usr/share/dependency-check/data \
            -e NVD_API_KEY=${{ secrets.NVD_API_KEY }} \
            owasp/dependency-check:latest \
            dependency-check.sh \
              --project "github-actions" \
              --scan /src \
              --nvdApiKey=${{ secrets.NVD_API_KEY }} \
              --format "HTML" \
              --out /src/dependency-check-report.html \
              --log /src/dependency-check.log || echo "Dependency-Check failed; check logs for details"

      - name: Upload Dependency-Check report
        if: always() # Ensure this step runs even if the previous step fails
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: dependency-check-report.html