name: CI

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  check-merged-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm install @octokit/rest

      - name: Check Merged PR Count
        id: check-merged-prs
        run: |
          node <<EOF
          const { Octokit } = require("@octokit/rest");
          const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

          async function getMergedPRCount() {
              const { data } = await octokit.pulls.list({
                  owner: process.env.REPO_OWNER,
                  repo: process.env.REPO_NAME,
                  state: "closed"
              });

              const mergedCount = data.filter(pr => pr.merged_at !== null).length;

              console.log(`Merged PR Count: ${mergedCount}`);
              if (mergedCount >= 5) {
                  process.exit(0); // Trigger next job
              } else {
                  process.exit(1); // Skip the pipeline
              }
          }

          getMergedPRCount();
          EOF
        env:
          GITHUB_TOKEN: ${{ secrets.ENV_GITHUB_TOKEN }}
          REPO_OWNER: chandana79895
          REPO_NAME: github-actions

      - name: Trigger Next Job
        if: success()
        run: echo "Enough PRs merged. Proceeding to next steps!"


  build:
    needs: check-merged-prs
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Configure Git user
        run: |
          git config --global user.email "manichandana7989@gmail.com"
          git config --global user.name "chandana79895"  

      - name: Bump version
        run: |
          npm version patch --no-git-tag-version

      - name: Dependency after version update
        run: npm ci    

      - name: Push changes
        run: |
          git add .
          git commit -m "Bump version new"
          git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/chandana79895/github-actions.git
          git pull
          git push origin develop