name: CI

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  check-prs:
    runs-on: ubuntu-latest
    outputs:
      pr_count: ${{ steps.get_pr_count.outputs.pr_count }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Get today's merged PR count
        id: get_pr_count
        run: |
          # Get today's date in YYYY-MM-DD format
          TODAY=$(date +%Y-%m-%d)

          # Fetch merged PRs from the API and count those merged today
          PR_COUNT=$(curl -s -H "Authorization: token ${{ secrets.ENV_GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=closed&base=develop" \
            | jq "[.[] | select(.merged_at != null and (.merged_at | split(\"T\") | .[0]) == \"$TODAY\")] | length")

          echo "PR count for today: $PR_COUNT"  # Debugging the PR count
          echo "::set-output name=pr_count::$PR_COUNT"  # Correct way to set output

  build:
    needs: check-prs
    if: ${{ needs.check-prs.outputs.pr_count > 1 }}  # Only run if more than 3 PRs are merged today
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log PR count for today
        run: echo "The PR count for today is ${{ needs.check-prs.outputs.pr_count }}"  # Debugging the value

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: npm ci

      - name: Configure Git User
        run: |
          git config --global user.email "manichandana7989@gmail.com"
          git config --global user.name "chandana79895"

      - name: Bump Version
        run: |
          npm version patch --no-git-tag-version

      - name: Reinstall Dependencies After Version Update
        run: npm ci    

      - name: Push Changes
        run: |
          git add .
          git commit -m "Bump version new"
          git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/chandana79895/github-actions.git
          git pull --rebase
          git push origin develop