name: CI

on:
  pull_request:
    types: [opened, closed]

jobs:
  handle-pr:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'opened' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm ci

      - name: Configure Git User
        run: |
          git config --global user.email "manichandana7989@gmail.com"
          git config --global user.name "chandana79895"

      - name: Bump Version
        id: bump_version
        run: |
          if [[ "${{ github.event.action }}" == "opened" ]]; then
            NEW_VERSION=$(npm version patch --no-git-tag-version)
            echo "New version is $NEW_VERSION"
            echo "::set-output name=new_version::$NEW_VERSION"
          fi

      - name: Update PR Description (On PR Opened)
        if: ${{ github.event.action == 'opened' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          NEW_VERSION=${{ steps.bump_version.outputs.new_version }}
          curl -X PATCH -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER \
            -d "{\"body\": \"Version bumped to $NEW_VERSION\"}"

  push-version:
    if: ${{ github.event.action == 'closed' && github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm ci

      - name: Configure Git User
        run: |
          git config --global user.email "manichandana7989@gmail.com"
          git config --global user.name "chandana79895"

      - name: Bump Version
        id: bump_version
        run: |
          NEW_VERSION=$(npm version patch --no-git-tag-version)
          echo "New version is $NEW_VERSION"
          echo "::set-output name=new_version::$NEW_VERSION"

      - name: Reinstall Dependencies After Version Update
        run: npm ci    

      - name: Push Changes
        run: |
          git add .
          git commit -m "Bump version new"
          git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/chandana79895/github-actions.git
          git pull --rebase
          git push origin develop

      - name: Create and Push Tag
        run: |
          NEW_VERSION=${{ steps.bump_version.outputs.new_version }}
          git tag $NEW_VERSION
          git push origin $NEW_VERSION