name: CI

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  check-merged-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install Dependencies
        run: npm install @octokit/rest

      - name: Create Node.js Script to Check Merged PRs
        run: |
          echo "
          const { Octokit } = require('@octokit/rest');
          
          const octokit = new Octokit({ auth: process.env.ENV_GITHUB_TOKEN });
          
          async function getMergedPRCount() {
              const { data } = await octokit.pulls.list({
                  owner: process.env.REPO_OWNER,
                  repo: process.env.REPO_NAME,
                  state: 'closed',
                  per_page: 100
              });
          
              const mergedCount = data.filter(pr => pr.merged_at !== null).length;
          
              console.log('Merged PR Count:', mergedCount);
              if (mergedCount >= 5) {
                  process.exit(0); // Trigger the next job
              } else {
                  process.exit(1); // Skip the pipeline
              }
          }
          
          getMergedPRCount();
          " > check-merged-prs.cjs

      - name: Run Node.js Script
        run: |
          node check-merged-prs.cjs
        env:
          ENV_GITHUB_TOKEN: ${{ secrets.ENV_GITHUB_TOKEN }}
          REPO_OWNER: chandana79895
          REPO_NAME: github-actions

  build:
    needs: check-merged-prs
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: npm ci

      - name: Configure Git User
        run: |
          git config --global user.email "manichandana7989@gmail.com"
          git config --global user.name "chandana79895"

      - name: Bump Version
        run: |
          npm version patch --no-git-tag-version

      - name: Reinstall Dependencies After Version Update
        run: npm ci    

      - name: Push Changes
        run: |
          git add .
          git commit -m "Bump version new"
          git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/chandana79895/github-actions.git
          git pull --rebase
          git push origin develop